### ISSUE TITLE
[PPC64] '-mmma' requiring instructions not guarded by __MMA__

### ISSUE THREAD

**Issue by spalicki** [uxlfoundation/oneDNN#3749]
After merging #3156 our automated conda build system started showing build issues where `__builtin_vsx_lxvp`, `__builtin_vsx_disassemble_pair` and similar instructions are directly used. Some code containing those is guarded with `__MMA__` e.g. entire `src/cpu/ppc64/ppc64_gemm_s8x8s32.cpp`, but code in `src/cpu/ppc64/ppc64_gemm_s8x8s32.hpp` is not:
```
 │ │ In file included from $SRC_DIR/src/cpu/ppc64/gemm/gemm_driver.cpp:38:
 │ │ $SRC_DIR/src/cpu/ppc64/ppc64_gemm_s8x8s32.hpp: In function 'int dnnl::impl::pack_N8_8bit_V2_lxvp_signed(dim_t, dim_t, const BufType*, dim_t, uint8_t*, bool) [with VecType = __vector(16) unsigned char; BufType = unsigned char]':
 │ │ $SRC_DIR/src/cpu/ppc64/ppc64_gemm_s8x8s32.hpp:2347:38: error: '__builtin_vsx_lxvp' requires the '-mmma' option
 │ │  2347 |             row1 = __builtin_vsx_lxvp(
 │ │       |                    ~~~~~~~~~~~~~~~~~~^
 │ │  2348 |                     0, reinterpret_cast<__vector_pair *>(&b[0]));
 │ │       |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
We need all code requiring `-mmma` build option guarded with `__MMA__`.

**Comment by spalicki** [comment]
@Tiwari-Avanish Can you help with this issue?

**Comment by vpirogov** [comment]
Related conda-forge build fail: https://github.com/conda-forge/onednn-feedstock/pull/86

**Comment by vpirogov** [comment]
Does it make sense to temporarily throw in `-mmma` option to at least make the packages buildable?

**Comment by spalicki** [comment]
> Does it make sense to temporarily throw in `-mmma` option to at least make the packages buildable?

Let me check if this would actually work, but according to GCC `The -mma option requires that the option -mcpu=power10 (or later) is enabled.`, which would break compatibility with any earlier CPU (older than late 2021).

**Comment by vpirogov** [comment]
That's definitely not perfect. Having no conda-forge packages for oneDNN is even worse.

Another alternative is guarding whole new implementations with `__MMA__`.

**Comment by spalicki** [comment]
Adding `-mcpu=power10 -mmma` (#3773) does seem to fix the build at the cost of breaking the compatibility with older CPU.

> Another alternative is guarding whole new implementations with `__MMA__`.

That was my first thought, but then I had to guard almost all of the GEMM implementation and still it created some other issues with reorder:
```
 │ │ $SRC_DIR/src/cpu/ppc64/ppc64_gemm_reorder.cpp:204:20: error: '__builtin_altivec_stxvl' requires the '-mcpu=power9' option and
 │ │ either the '-m64' or '-mpowerpc64' option
```
In the end it would be better to just revert the changes in: [9334ebc](https://github.com/uxlfoundation/oneDNN/commit/9334ebca382d485a94cbe4f0b0307bdb0b676fca) (#3156) and [d42cbaa](https://github.com/uxlfoundation/oneDNN/commit/d42cbaab2c62dc27707ee624d76289678953389e).

**Comment by spalicki** [comment]
@vpirogov @Tiwari-Avanish
The change adding `-mcpu=power10 -mmma` to cross-compilers has been merged to main and 3.9 release branch.

**Comment by vpirogov** [comment]
Workaround: #3788

**Comment by vpirogov** [comment]
While we restored oneDNN builds for PowerPC I'm keeping this issue open in case someone is interested in restoring support for older processors.

**Comment by kwizart** [comment]
@vpirogov fedora build is also affected... (FYI, fedora-43 still build with -mcpu=power8 -mtune=power8 ).

That said, I'm not sure why this "-mcpu=power10 -mmma" options is added globally. The usual way to solve this is to add theses options only to the few files actually using -mmma. This assumes that older CPU will select an alternatives implementation. So this may assumes the code is built twice or that separates functions/files exists for both cpu...

**Comment by vpirogov** [comment]
> That said, I'm not sure why this "-mcpu=power10 -mmma" options is added globally. The usual way to solve this is to add theses options only to the few files actually using -mmma. This assumes that older CPU will select an alternatives implementation.

I agree that we should have fallback to alternative implementations for older processors. Unfortunately the way new implementations were introduced in PR #3156 makes it a non-trivial exercise. We would appreciate help addressing this issue from someone with access to necessary testing infrastructure.

**Comment by kwizart** [comment]
(forwarded to fedora-ppc team)

**Comment by Tiwari-Avanish** [comment]
Hi @spalicki,

I want to restore the changes for powerpc code that was reverted back https://github.com/uxlfoundation/oneDNN/pull/3156

I will fix the below issue as well. 

``` │ │ In file included from $SRC_DIR/src/cpu/ppc64/gemm/gemm_driver.cpp:38:
 │ │ $SRC_DIR/src/cpu/ppc64/ppc64_gemm_s8x8s32.hpp: In function 'int dnnl::impl::pack_N8_8bit_V2_lxvp_signed(dim_t, dim_t, const BufType*, dim_t, uint8_t*, bool) [with VecType = __vector(16) unsigned char; BufType = unsigned char]':
 │ │ $SRC_DIR/src/cpu/ppc64/ppc64_gemm_s8x8s32.hpp:2347:38: error: '__builtin_vsx_lxvp' requires the '-mmma' option
 │ │  2347 |             row1 = __builtin_vsx_lxvp(
 │ │       |                    ~~~~~~~~~~~~~~~~~~^
 │ │  2348 |                     0, reinterpret_cast<__vector_pair *>(&b[0]));
 │ │       |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Can you help me to understand what was the root cause here.

**Comment by vpirogov** [comment]
> Can you help me to understand what was the root cause here.

@Tiwari-Avanish, the issue here is that newly introduced code uses `mma` built-ins that:
1. Requires `-mmma` flag during build time.
2. Are not available on power8 systems.

oneDNN builds with `-mnative`, which enables `-mpower10 -mmma` on power10 systems. You need to guard these implementations with `__MMA__`  macro and test that oneDNN with your changes builds and works correctly on power8 system in addition to power10.

**Comment by spalicki** [comment]
@Tiwari-Avanish Please rebase and repost your change including: #3156 and fix from [d42cbaab2c62dc27707ee624d76289678953389e](https://github.com/uxlfoundation/oneDNN/commit/d42cbaab2c62dc27707ee624d76289678953389e) into a new PR, we can continue the discussion there.

**Comment by Tiwari-Avanish** [comment]
Sorry, for the late reply.
Thanks @vpirogov @spalicki  for explaining the root cause and guiding me. 
I have open the PR with the changes https://github.com/uxlfoundation/oneDNN/pull/4002, please review the PR.
